apiVersion: v1
kind: Service
metadata:
  name: dice-game-service
  namespace: devops
spec:
  type: ClusterIP
  selector:
    app: dice-game
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000